def throw_error(err_msg):
    """Functions prints an error message and terminates running program.

    :param err_msg: Error message string.
    """
    print(f"Error: {err_msg}")
    exit(1)
